### ISSUE TITLE
Team 73 - The Corgi's Feeback

### ISSUE THREAD

**Issue by cliftondavies** [dannisonarias/Object-Oriented-Program-Project-tic-tac-toe-#8]
0. Beautiful project!
1. Amazing README, very detailed and informative!
2. Check [OOP Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle). Ideally classes should have a single functionality.
3. Alternative Solution: Try implementing with **Hash** for board positions.

**Comment by dannisonarias** [comment]
addressed
